language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
    - travis_retry composer self-update
    - travis_retry composer global require hirak/prestissimo
    - travis_retry composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

notifications:
    script:
        - "phpunit -v --coverage-text --colors=never --stderr"

after_success:
    - bash <(curl -s https://codecov.io/bash)
    - php vendor/bin/codacycoverage clover build/logs/clover.xml
