language: php

php:
    - 5.6
    - 7.0
    - hhvm

before_script:
    - travis_retry composer self-update
    - travis_retry composer global require hirak/prestissimo
    - travis_retry composer install --prefer-dist --no-interaction

after_script:
    - php vendor/bin/codacycoverage clover build/logs/clover.xml

notifications:
    script:
        - "phpunit --process-isolation"
